### ISSUE TITLE
Bug: push protection bypass alerts are not reopened

### ISSUE THREAD

**Issue by CallMeGreg** [advanced-security/probot-security-alerts#68]
When a user who's NOT on the `SECURITY_ALERT_CLOSE_TEAM` bypasses push protection for [a reason that results in a closed alert](https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/push-protection-for-repositories-and-organizations#about-push-protection-for-repositories-and-organizations), the alert is not reopened by the app.

**Comment by kenmuse** [comment]
There is now a native feature that supports this -- [delegated bypass](https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/push-protection-for-repositories-and-organizations#enabling-delegated-bypass-for-push-protection)
